### ISSUE TITLE
Adopt split repo: _python-analytics-admin_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10889]
Migrate the split-repo https://github.com/googleapis/python-analytics-admin to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
Adding `blocked` label while we determine how to migrate this repository. The repository contains samples which should be migrated to a new repository https://github.com/googleanalytics/python-docs-samples (see similar repository for dotnet https://github.com/googleanalytics/dotnet-docs-samples) instead of the cloud specific one https://github.com/GoogleCloudPlatform/python-docs-samples.

Please check with @ikuleshov before completing any work related to the migration.

**Comment by suztomo** [comment]
The issues tab is now empty.
