### ISSUE TITLE
Adopt split repo: _python-cloudbuild_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#10998]
Migrate the split-repo https://github.com/googleapis/python-cloudbuild to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
A change is needed to the generator to specify additional dependencies that are required when multiple APIs are shipped together. In this case, `grpc-google-iam-v1` is required by cloud build v2 but not cloud build v1. Since cloud build v1 is the default version, we need to find a way to add the dependency  `grpc-google-iam-v1` to setup.py

```
    # grpc-google-iam-v1 is required by cloud build v2 however setup.py does not reflect this.
    # The issue is that both v1 and v2 are generated which have different requirements for setup.py files.
    # The setup.py for v2 is clobbered by the setup.py for v1 which does not require grpc-google-iam-v1.
    assert 1 == s.replace(
        library / "setup.py",
        r"""\"protobuf>=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5\",\n""",
        """\"protobuf>=3.19.5,<5.0.0dev,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5\",
    "grpc-google-iam-v1 >= 0.12.4, < 1.0.0dev",\n""",
    )
```
