### ISSUE TITLE
Adopt split repo: _python-grafeas_

### ISSUE THREAD

**Issue by vchudnov-g** [googleapis/google-cloud-python#11041]
Migrate the split-repo https://github.com/googleapis/python-grafeas to https://github.com/googleapis/google-cloud-python.

The migration readiness criteria are the following, which we track via GitHub labels on this issue. These criteria apply to the split repo we are migrating from:
- No open issues
- No open PRs
- No handwritten samples
- No system tests
- No client-specific customizations

**Comment by parthea** [comment]
Marking this bug as blocked because this client is unique. The [default endpoint](https://github.com/googleapis/python-grafeas/blob/main/owlbot.py#L50) and [default credentials](https://github.com/googleapis/python-grafeas/blob/main/owlbot.py#L99) are removed from the generated code. There is no other python client with this requirement. I'm going to keep this bug open so we can track discussions related to migrating the repository in one place.

**Comment by parthea** [comment]
FYI @vchudnov-g
