### ISSUE TITLE
Video Intelligence API - returns error - Calculation Error - Request task has error from parents. 

### ISSUE THREAD

**Issue by mohittalele** [googleapis/google-cloud-python#11586]
Hello All,

In our team we have been using video intelligence API for speech transcription. 

The API was running fine for about a year now. However lately we have been getting below error ( see at the end) . 

The error is intermittent that means for about 20 tries to video intelligence API about 15 fails and another 5 are successful in giving transcripts.  This error slows us down and availability of our internal systems (SLA) are greatly affected.

#### Environment details

  - OS type and version: `Windows 11, Linux Ubuntu 20.04`
  - Python version: `Python 3.6.8 :: Anaconda, Inc.`
  - pip version: `pip 21.2.2 from C:\ProgramData\Anaconda3\envs\vyper\lib\site-packages\pip (python 3.6) `
  - `google-cloud-videointelligence` version: `2.1.0`

#### Steps to reproduce

  1.  Use the video with audio in german/english language with length about 45min-90min, approx around1.4Gi
  2.  Trigger the video intelligence API 

#### Code example

```python
# example
from google.cloud import videointelligence
import os 
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = r'path_tojson_file.json'
os.environ['HTTP_PROXY'] = HTTP_PROXY
os.environ['HTTPS_PROXY'] = HTTPS_PROXY
video_client = videointelligence.VideoIntelligenceServiceClient()
features = [videointelligence.Feature.SPEECH_TRANSCRIPTION]

config = videointelligence.SpeechTranscriptionConfig(
    language_code="en-US", enable_automatic_punctuation=True
)
video_context = videointelligence.VideoContext(speech_transcription_config=config)

operation = video_client.annotate_video(
    request={
        "features": features,
        "input_uri": "gs://tst_gcpvideo_rtlzwei_bucket/ted.mp4",
        "video_context": video_context,
    }
)
try :
    result = operation.result(timeout=60000)
except Exception as e: 
    print(e)
print(result)
```

#### Response from API
```
# example
annotation_results {
  input_uri: "/tst_gcpvideo_my_company_bucket/ted.mp4"
  error {
    code: 13
    message: "Calculator error."
    details {
      type_url: "type.googleapis.com/google.rpc.Status"
      value: "\010\t\022$Request task has error from parents."
    }
    details {
      type_url: "type.googleapis.com/google.rpc.Status"
      value: "\010\t\022&Operation task has error from parents."
    }
  }
}

```
The documentation do not speak about the code 13 as such. 

Thanks!

**Comment by vchudnov-g** [comment]
Hi @mohittalele . Thanks for filing this issue! This seems like an API-level issue (since the problem arises from the API response), not a client library-level issue. You can confirm this by trying the request using `curl`, for example. In that case, the issue should be filed against the API via  https://issuetracker.google.com/savedsearches/5084810. In general, for API issues consult https://cloud.google.com/support/docs/issue-trackers to see where to file against the correct API team so they can respond to problems promptly.

I'll ping the team internally to take a look at this issue, but I would recommend you file an issue against the issue tracker and link to it from this GitHub issue. That way the  various teams can sure to see it and respond. 

Thanks!

**Comment by vchudnov-g** [comment]
@mohittalele , I heard back from the API team. Would you be able to reproduce the issue and then provide us with the operation name you receive so that they can further look into it? Thanks!

**Comment by mohittalele** [comment]
This issue was resolved when I raised an issue in google group. We can close this issue. Our system have not experienced same error again after fix.

**Comment by vchudnov-g** [comment]
OK, thanks!
