### ISSUE TITLE
"The provided API key is expired."

### ISSUE THREAD

**Issue by Strvm** [googleapis/google-cloud-python#11908]
Hello,

I am programmatically creating API keys using the google-cloud-api-keys library. 

Issue is, when I query the Places API, I get this error message:

GET: `https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJi45AqqWxe0gRq-HByJInM6o&fields=place_id&key=<CREATED_KEY>`
```json
{

    "error_message": "The provided API key is expired.",
    "html_attributions": [],
    "status": "REQUEST_DENIED"

}
```

Issue is the API key does exists. But after waiting like 10 minutes the API key starts to work out of no where. How can this delay be fixed? 

I want to be able to create keys on the fly with their own restrictions, but this issue is making it very hard to handle.

I read that this could be due to a "propagation" issue and might have to wait 10 minutes before being able to use my key. How can this be possible?

**Comment by parthea** [comment]
Hi @Strvm,

Please file an issue in the [public issue tracker for the Google Maps Places API](https://developers.google.com/maps/documentation/places/web-service/support#bugs). I'm going to close this issue as it is an issue with the API rather than the client library code in this repository.

For issues related to your API key and specific to your project, I recommend filing a support case by following the guide here to open a personalized communication channel: https://developers.google.com/maps/support/#creating-a-support-case
