### ISSUE TITLE
Datacatalog SearchCatalogRequest fails when returning more than one page when using a policytag query

### ISSUE THREAD

**Issue by tommyhutcheson** [googleapis/google-cloud-python#12257]
Datacatalog SearchCatalogRequest fails to return a response when iterating over the 2nd page of responses when using policytag or policytagid queries.

This code below will reproduce the same problem as long as you have 21 tables with the policytagid on one of the columns in each table.

```
from google.cloud.datacatalog_v1 import DataCatalogClient, SearchCatalogRequest
from pydantic import BaseSettings


class AppConfig(BaseSettings):
    project_id: str
    policytagid: str


def datacatalog_table_search(app_config, client):

    scope = SearchCatalogRequest.Scope(include_project_ids=(app_config.project_id,))
    query = f"projectid={app_config.project_id} policytagid={app_config.policytagid}"
    for entry in client.search_catalog(scope=scope, query=query):
        print(f"This is my entry table {entry.fully_qualified_name}")


def main():
    app_config = AppConfig()

    client = DataCatalogClient()

    datacatalog_table_search(app_config, client)


if __name__ == '__main__':
    main()
```

> grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Searches from all regions failed. Possible errors are: internal error in search backend"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:***.***.***.***:443 {grpc_message:"Searches from all regions failed. Possible errors are: internal error in search backend", grpc_status:3, created_time:"2024-02-02T14:20:39.847206975+00:00"}"

**Comment by parthea** [comment]
Hi @tommyhutcheson , 

Thanks for sharing sample code and the stack trace.  Based on the error in the stack trace `internal error in search backend`, this is an API specific issue and needs to be resolved by the Data Catalog API team. I see that there is an internal issue created (b/321748619) which is already opened for the API team.  You may also file an issue in the [public issue tracker for the Data Catalog API](https://issuetracker.google.com/savedsearches/5487242) in case you want to receive live updates from the product team on this issue. 

I'm going to close this issue as it is an issue with the API rather than the client library code in this repository but please feel free to open a new issue if you encounter other issues with the client library.
