### ISSUE TITLE
Partial Search Query Not Returning Expected Results

### ISSUE THREAD

**Issue by Matroid1998** [googleapis/google-cloud-python#12796]
### Summary of the issue

I have created a datastore and engine for structured data in Vertex AI. When performing a search query with the term "s", some documents are successfully retrieved. However, when I modify the search query to "sma", no documents are returned.

API used : SearchRequest

**Comment by ohmayr** [comment]
Hi @Matroid1998, Please open a new issue using the following template [File a Bug](https://github.com/googleapis/google-cloud-python/issues/new?assignees=&labels=type%3A+bug%2Ctriage+me&projects=&template=bug_report.yaml) and make sure to populate all the sections for the quickest possible resolution to your issue.

Closing this issue since we do not have enough information to investigate this and have asked the user to open a new issue.
