### ISSUE TITLE
v2alpha doesnot support HiveQL whereas v2 supported it

### ISSUE THREAD

**Issue by zeedeloitte** [googleapis/google-cloud-python#13161]
### Determine this is the right repository

- [X] I determined this is the correct repository in which to report this feature request.

### Summary of the feature request

Why is the alpha version of v2 only limited to TERADATA and doesnot list HiveQL as a supported dialect? 
https://cloud.google.com/python/docs/reference/bigquerymigration/latest/google.cloud.bigquery_migration_v2alpha.types.TranslateQueryRequest.SqlTranslationSourceDialect

Problem statement: 

Unfortunately, the BigQuery Migration V2alpha API does not explicitly list HiveQL as a supported source dialect.

Can you update the list of source dialects currently supported in the V2alpha API.

the v2alpha API doesnot support the dialect HIVEQL which was supported by previous v2 API. 

as you can see only TERADATA is listed here: 

https://cloud.google.com/python/docs/reference/bigquerymigration/latest/google.cloud.bigquery_migration_v2alpha.types.TranslateQueryRequest.SqlTranslationSourceDialect

can you please confirm if bigquery_migration_v2alpha supports Hive QL dialect? as previous version of API v2 supported it. 

**The problem with the previous version v2 is that it only takes input/output bucket from GCP and doesnot return a translation result like the v2alpha API.** 

### Desired code experience

Translates input queries from source dialects (why doesn't this api support HiveQL even when v2 previous version of API did) to GoogleSQL.

`
# code
from google.cloud import bigquery_migration_v2alpha

def sample_translate_query():
    # Create a client
    client = bigquery_migration_v2alpha.SqlTranslationServiceClient()

    # Initialize request argument(s)
    request = bigquery_migration_v2alpha.TranslateQueryRequest(
        parent="parent_value",
        **source_dialect="TERADATA",** 
#**_DOESNOT SUPPORT  HIVEQL unlike v2. Just says TERADATA. ADD HiveQL!_**
        query="query_value",
    )

    # Make the request
    response = client.translate_query(request=request)

    # Handle the response
    print(response)`
    
URL code taken from: https://cloud.google.com/python/docs/reference/bigquerymigration/latest/google.cloud.bigquery_migration_v2alpha.services.sql_translation_service.SqlTranslationServiceClient

### Expected results

**The problem with the previous version v2 is that it only takes input/output bucket from GCP and doesnot return a translation result as a string like the v2alpha API. And v2alpha API doesnot support HiveQL as a dialect as it is not listed under **  https://cloud.google.com/python/docs/reference/bigquerymigration/latest/google.cloud.bigquery_migration_v2alpha.types.TranslateQueryRequest.SqlTranslationSourceDialect

### API client name and version

bigquery_migration_v2alpha

**Comment by parthea** [comment]
Hi @zeedeloitte,

The client library for BigQuery Migration v2alpha is automatically generated using the `*.proto` files which live here: https://github.com/googleapis/googleapis/tree/master/google/cloud/bigquery/migration/v2alpha.  Regrettably, the `SqlTranslationSourceDialect` enum only includes `TERADATA` as you pointed out. 

I found that although `TranslateQueryRequest` [exists in the proto](https://github.com/search?q=repo%3Agoogleapis%2Fgoogleapis%20TranslateQueryRequest&type=code), there is no API specific documentation for it [here](https://cloud.google.com/s/results/bigquery/docs?q=TranslateQueryRequest).

Regrettably for questions specific to the API rather than the client library, I need to redirect you to the API support channel so you can get better quality answers. 

Please use the [public issue tracker here](https://issuetracker.google.com/issues/new?component=187149&template=0) to communicate directly with the BigQuery API team.   The link to the public documentation for the `BigQuery Migration` API lives here: https://cloud.google.com/bigquery/docs/reference/migration . On this page, there are additional resources to get API specific support. For support, see https://cloud.google.com/bigquery/docs/getting-support.

I'm going to close this issue but please feel free to open a new issue if you encounter any client library bugs.
