### ISSUE TITLE
Clarification on `ConversationalSearchServiceClient` vs `SearchServiceClient` in Google Python SDK

### ISSUE THREAD

**Issue by SGINJ** [googleapis/google-cloud-python#13180]
### Determine this is the right repository

- [X] I determined this is the correct repository in which to report this feature request.

### Summary of the feature request

Hello,

I am currently using the Google Python SDK and have come across two classes: `discoveryengine.ConversationalSearchServiceClient` and `discoveryengine.SearchServiceClient`. I am trying to understand the differences between these two clients, particularly in the context of their capabilities and use cases.

From my understanding:
- `ConversationalSearchServiceClient` seems to support multi-turn search, allowing for a conversational experience by maintaining session context across multiple queries.
- `SearchServiceClient`, on the other hand, appears to be used for standard search operations without the conversational context.

Given that both clients can perform search operations (with the same capabilities if I'm not wrong), I am curious about the specific scenarios or advantages of using one over the other when multi-turn features are not required. Is there any additional documentation or guidance on when to use each client?

Additionally, I noticed that the documentation and examples available are somewhat limited and mostly auto-generated. If there are any resources or examples that provide a deeper insight into these clients, I would greatly appreciate it.

Thank you for your assistance!

### API client name and version

google-cloud-discoveryengine = "0.12.2"

**Comment by LucaPascucci** [comment]
Same doubts for me

**Comment by parthea** [comment]
Hi @SGINJ @LucaPascucci,

Regrettably for questions specific to the API rather than the client library, I need to redirect you to the API support channel so you can get better quality answers.

Please use the [public issue tracker here](https://issuetracker.google.com/issues/new?component=911831&template=1480251) to communicate directly with the Discovery Engine API team.   The link to the public documentation for `Discovery Engine` lives here: https://cloud.google.com/generative-ai-app-builder/docs/introduction . On this page, there are additional resources to get API specific support. For support, see https://cloud.google.com/generative-ai-app-builder/docs/support and for samples refer to https://cloud.google.com/generative-ai-app-builder/docs/samples. You can also file an issue [here](https://github.com/GoogleCloudPlatform/python-docs-samples/issues) to request specific code samples for the API.

I'm going to close this issue but please feel free to open a new issue if you encounter any bugs, or features for the client library.

**Comment by parthea** [comment]
https://issuetracker.google.com/issues/new?component=911831&template=1480251 is the correct link to the API specific issue tracker
