### ISSUE TITLE
Docs for autogen libraries are minimal, unsat for GA

### ISSUE THREAD

**Issue by tseaver** [googleapis/google-cloud-python#5911]
There is nothing like usage docs for any of these libraries.

/cc @theacodes

**Comment by meredithslota** [comment]
Closing this; the autogen process has changed quite a bit since it was filed. If you feel like this hasn't been addressed, we can figure out which autogen'd libraries are still impacted.  E.g. https://github.com/googleapis/python-bigquery-datatransfer + docs here: https://googleapis.dev/python/bigquerydatatransfer/latest/index.html
