### ISSUE TITLE
 Logging: set logName with google.cloud.logging.Client().get_default_handler()

### ISSUE THREAD

**Issue by ZeeD** [googleapis/google-cloud-python#6235]
I waited for a response for the ticket #6206  but I had none, so I'm opening a new ticket.

**Comment by tseaver** [comment]
I will reopen #6206, but you will need to explain your usecase more clearly -- there is nothing magical about how the handler name is set during construction compared to setting it afterward.

**Comment by jstafford5380** [comment]
Sorry for resurrecting but I feel like this wasn't necessarily answered. I'm not sure if we're encountering the same issue, but it seems similar and wouldn't be specific to app engine. When I do the following:

```python
logging_client = google_log.Client(project=project_id)
default_handler = logging_client.get_default_handler()
default_handler.name = 'my-api'
```

I've also tried this in tandem:

```python
# some_other_file.py
import logging

logger = logging.getLogger('my-api')
```

with the same outcome which is:

It adds a label to the log entry as `python_logger: 'my-api' but does nothing to the log name. The log name (literally `logName` in the log entry in GCO) remains as `projects/my-project-name/logs/python`. 

I can at least speak for the .NET sdk, we can set the log name such that it would come out like `projects/my-project/logs/my-api`. This is so that it becomes selectable in the log names drop down in the logs explorer. The objective being that ANY log generated by this application would be in that particular log "file".  This is useful particularly when you have a project that has multiple components running, you can see the separate logs. Like this:

![image](https://github.com/googleapis/google-cloud-python/assets/47302800/ef7e69f9-6f76-4a64-802c-f3d8ccf3c4dd)

vs. how it is currently where every log is just called 'python'

For contrast, I believe the label is good for tagging a log *scope* (e.g. an operation or some particular grouping within the log) whereas the log NAME would be the entire log stream for the application.

Is there a way to achieve this?

**Comment by parthea** [comment]
@jstafford5380,

Please could you file a new issue [here](https://github.com/googleapis/python-logging/issues) as the `python-logging` repository contains the code for the `google-cloud-logging`.
