### ISSUE TITLE
Release 'api_core-1.6.0a2'? or 'api_core-1.5.1'?

### ISSUE THREAD

**Issue by tswast** [googleapis/google-cloud-python#6326]
I'd like to use the changes from https://github.com/googleapis/google-cloud-python/pull/6310 in the library I'm working on.

Not sure about the version number for that one, since:

- I don't know what else has been released since 1.6.0a1
- I don't know what is intended by 1.6.0a1 in https://github.com/googleapis/google-cloud-python/pull/6267 (is it a pre-release?)

**Comment by tseaver** [comment]
@tswast I believe @lukesneeringer is the one who can answer your question about PR #6267 and the `api_core-1.6.0a1` release.

My take:  given that we follow the "keep `master` releasable at all times" development practice, I believe that we should move the changes from #6267 off onto a branch (or even just revert it and re-merge later) to allow for making an `api_core-1.5.1` release from master, including your bugfix from #6310.

As an alternative, we could make an `api_core-1.5-maint` branch from 7527a4ed546f7f202529a8d323302302fd728ee4 (the last commit on `master` touching `api_core/` before #6267), and cherry pick e368317c9ff99db572a0463e9dbd5e77294cfcd4 into it from #6310 in order to make the `api_core-1.5.1` release you need.
