### ISSUE TITLE
[Firestore] implement `__eq__` for public api types.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6552]
None of the public API types implement isEquals (__eq__)

**Comment by schmidt-sebastian** [comment]
Note that instead of `isEqual`, Python's own equal semantics should we used. I believe that some types (such as DocumentReferences) already implement custom `__eq__` functions. It is however missing from other prominent types such as DocumentSnapshots. 

Ideally, a custom equals function would exist at least on CollectionReference, Query, DocumentReference, DocumentSnapshot and QuerySnapshot.

**Comment by tseaver** [comment]
Candidate list from the types exported from `google.cloud.firestore`:

- [ ] `CollectionReference`
- [ ] `DocumentReference`
- [ ] `DocumentSnapshot`
- [ ] `ExistsOption`
- [ ] `GeoPoint`
- [ ] `LastUpdateOption`
- [ ] `Query`

The types in `enums` and `types` already have equality semantics.

I believe the following do *not* need equality semantics:

- `Transaction` (? -- transient)
- `Watch` (? -- transient)
- `WriteBatch` (? -- transient)
- `WriteOption` (? -- abstract)

Additional types exported by `google.cloud.firestore_v1beta1` (these should likely be exported from the non-versioned module as well):

- [ ] `ArrayRemove`
- [ ] `ArrayUnion`
