### ISSUE TITLE
[Firestore] Refactor Python Transaction layer to better match other SDKs.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-python#6557]
The Transaction API is vastly different: Instead of offering a Transaction type and a run_transaction() function, a transaction object has to be passed as an optional argument to all WriteBatch methods.

b/76423649

**Comment by tseaver** [comment]
`run_in_transaction` is a Spanner-only construct.  `datastore` offers `Transaction` as a subclass of `Batch`, and handles the get-a-transaction-id dance in its `__enter__`.  See: https://googleapis.github.io/google-cloud-python/latest/datastore/transactions.html

**Comment by crwilcox** [comment]
Assigning myself. I need to figure out what this exactly means.

**Comment by tseaver** [comment]
FTR:

- Spanner uses a "unit of work" callback, and then runs it in a loop under the covers to handle the  various `ABORTED` bits which can be triggered during either reads (by the UoW callable) or at commit time.
- Datastore exposes using its `Batch` and `Transaction` objects as context managers:  `commit` happens if the `with` block exits without raising an exception.

Firestore basically follows Datastore's pattern.

**Comment by crwilcox** [comment]
I think matching the datastore semantics makes the most sense here.

**Comment by crwilcox** [comment]
@tseaver, if you can prioritize looking into this? Other clients have `get` and `getAll`

https://github.com/googleapis/nodejs-firestore/blob/d307e465aaf8a2709ae0822075488ecb481babf7/dev/src/transaction.ts#L184

So, we would like to add a `transaction.getAll(documentReferences)` call. Also probably a `transaction.get(documentReference)` call. 

node also supports queryReferences to get. It may be good to do the same in python.
