### ISSUE TITLE
[App Engine] Can't find library for app engine

### ISSUE THREAD

**Issue by tarasBilobran** [googleapis/google-cloud-python#6654]
Hi i can't find source code for App Engine.
Is it really the only way to install App Engine library is by using 'gcloud'?

**Comment by tseaver** [comment]
@tarasBilobran This repository is not where AppEngine stuff is maintained.  See https://cloud.google.com/appengine/docs/standard/python/download and related pages.

**Comment by bagpoint-dev** [comment]
@tseaver That page only includes instructions to install a local SDK allowing to interact with Google App Engine via the command line - and only includes instructions for usages with Python 2.7. I'm looking for a Python 3.5+ library which would allow to programmatically fetch and update metadata of Google App Engine instances. Much like https://googleapis.github.io/google-cloud-python/latest/resource-manager/index.html, but for Google App Engine.

I'm looking for a library like this for the purpose of helping me create a dashboard for my company to be able to easily check and update on the status of apps deployed in App Engine. The library mentioned above (Python Client for Google Cloud Resource Manager) only gets me half way there, since although it allows me to create and list new Google Cloud projects, it doesn't allow me to retrieve data about App Engine instances, or to generate new ones.

**Comment by tseaver** [comment]
@bagpoint-dev This repository is where we maintain / relase Python client libraries for various Google Cloud APIs, and has little or nothing to do with GAE (except that the libraries can be used on the "Flexible" version of GAE).  Please use one of the "Support" resources on the [GAE docs page](https://cloud.google.com/appengine/docs/) to ask about such a feature.

**Comment by xassbit** [comment]
@tseaver It's confusing since in places such as the Google Cloud Console services like BigQuery and IoT (for which there are libraries available from this project) are display the same level of App Engine, making it look as if Google App Engine would be one of the multiple services under the Google Cloud umbrella.
