### ISSUE TITLE
Firestore: add a batch read method for a firestore collection

### ISSUE THREAD

**Issue by Wade-McDaniel** [googleapis/google-cloud-python#6801]
Greetings,

I'm trying to read all of a firestore collection out into a file on my local machine using python, and I always get "google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded". I've even tried the code below to try to get around this by reading 500-item chunks from the collection, but it does the same thing.

```
#!/usr/bin/python

#had to run this to get this to run with ActiveState Python 3.6.0 as 3.6.1 isn't available from ActiveState yet: python -m pip install protobuf==3.6.0

from google.cloud import firestore
import json, math, time

db = firestore.Client()
users_ref = db.collection(u'users')
batchSize = 500
batches = math.floor(len(list(users_ref.get())) / 500)

for i in range(0, batches):
	with open('file.txt', 'w') as file:
		print(i, " of ", batches)
		docs = users_ref.offset(i * batchSize).limit(batchSize).get()
		file.write(json.dumps({doc.id: doc.to_dict() for doc in docs}))
		time.sleep(1)
```

Maybe you could add a batch get method to solve this? This is totally time-independent, so it could take an hour for all I care, as i plan to run this once a day or so.

Thank you!

**Comment by tseaver** [comment]
@Wade-McDaniel The call to `users_ref.get()` actually already returns the data you need:  it is an iterator of the snapshots of all the documents in the collection.  Can you try the following?

```python
import json

from google.cloud import firestore

db = firestore.Client()
users_ref = db.collection(u'users')
snapshots = list(users_ref.get())
mapping = {
    snapshot.id: snapshot.to_dict() for snapshot in snapshots
}
json.dump(mapping, file)
```

Please re-open / follow up if this method does not work for your usecase.

**Comment by jneeven** [comment]
Hi, I find myself in a similar situation, except in my case it's the call to `collection.get()` that causes the exception. For now the only solutions I've found are:
- Setting the timeout in `get` to some large number that grows as my database grows (which is tough since there is no way to query how big a collection is without needing to first retrieve all its documents)
- First calling `list_documents` to get a bunch of references, and then manually calling `get()` on all of those. Even just the call to `list_documents` is at least 4 times as slow as calling `get` on the collection directly, and then I don't even have any snapshots yet...

What is the proper solution here? Thanks!
