### ISSUE TITLE
Pubsub: clients emit pending deprecation warnings

### ISSUE THREAD

**Issue by JoshuaFox** [googleapis/google-cloud-python#6887]
(See [Google Group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cloud-pubsub-discuss/A53nuoc3Eb4/LH6gwaXfDgAJ) )

With the Python pubsub package v 0.39.0,  a simple call to pubsub_v1.SubscriberClient() gives  warnings from deep in Google code
```
             
 publisher/client.py:89: PendingDeprecationWarning: The `channel` argument is deprecated; use `transport` instead.
  ...
  subscriber/client.py:83: PendingDeprecationWarning: The `channel` argument is deprecated; use `transport` instead.
  ...

```
This apparently incorrect channel is created inside Google code, e.g.  `google.cloud.pubsub_v1.subscriber.client.Client#__init__`

Although keeping ahead of deprecation can be challenging, Google's _own_ code  should avoid warnings and do whatever Google says is the official way.

**Comment by tseaver** [comment]
@theacodes Both the [publisher client](https://github.com/googleapis/google-cloud-python/blob/33eb5b5894427c839bd091d1af39a54186acc410/pubsub/google/cloud/pubsub_v1/publisher/client.py#L73-L85) and the [subscriber client](https://github.com/googleapis/google-cloud-python/blob/33eb5b5894427c839bd091d1af39a54186acc410/pubsub/google/cloud/pubsub_v1/subscriber/client.py#L66-L79) have comments which specify that they are passing a custom client in order to override maximum message size and keepalive options.  Should those fixes still be needed?  I guess we could add synth replacements to the `*_grpc_transport.py` files such that the local `create_channel` method passed along appropriate values.

@lukesneeringer I've asked elsewhere, but have no idea why the GAPIC generator is deprecating passing a channel:  can you explain here?
