### ISSUE TITLE
Firestore: ExistsOption with document update

### ISSUE THREAD

**Issue by Tenzer** [googleapis/google-cloud-python#7554]
[The documentation](https://googleapis.github.io/google-cloud-python/latest/firestore/document.html#google.cloud.firestore_v1beta1.document.DocumentReference.update) mentions that an `option` argument can be set on the `DocumentReference.update()` method to say that the document should be created if it doesn't already exists.

I've been trying to find out how that's supposed to work, and haven't been able to, as it seem's like to me that the way to do it is blocked explicitly in the code.

This has been tested with the latest version of google-cloud-firestore == 0.31.0 and Python 3.7.2:

```python
>>> from google.cloud import firestore
>>> database = firestore.Client()
>>> doc_ref = database.collection("col").document("doc")
>>> doc_ref.get().exists
False
>>> doc_ref.update({"foo": "bar"})  # Fails as expected
Traceback (most recent call last):
[... Truncated ...]
google.api_core.exceptions.NotFound: 404 No document to update: projects/<my project>/databases/(default)/documents/col/doc
>>>
>>>
>>> doc_ref.update({"foo": "bar"}, firestore.ExistsOption(exists=False))  # Should work, but doesn't
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<virtualenv path>/lib/python3.7/site-packages/google/cloud/firestore_v1beta1/document.py", line 370, in update
    batch.update(self, field_updates, option=option)
  File "<virtualenv path>/lib/python3.7/site-packages/google/cloud/firestore_v1beta1/batch.py", line 110, in update
    raise ValueError("you must not pass an explicit write option to " "update.")
ValueError: you must not pass an explicit write option to update.
```
My attempt at setting the option is based on doing the same as what's done here, but with an opposite boolean value:
https://github.com/googleapis/google-cloud-python/blob/c2b5dfcdec781e9379015975745c3e55f6899ef6/firestore/google/cloud/firestore_v1beta1/_helpers.py#L816-L817

But it's not allowed due to the check here:
https://github.com/googleapis/google-cloud-python/blob/c2b5dfcdec781e9379015975745c3e55f6899ef6/firestore/google/cloud/firestore_v1beta1/batch.py#L109-L110

So I don't quite know how I otherwise am supposed to change the setting in order to achieve an upsert-like functionality.

**Comment by tseaver** [comment]
@Tenzer For "upsert" semantics, use [`Document.set`](https://googleapis.github.io/google-cloud-python/latest/firestore/document.html#google.cloud.firestore_v1beta1.document.DocumentReference.set), but *don't* pass an option.  E.g.:

```python
>>> doc_ref.set({"foo": "bar"})
```

To merge fields from the passed dict int any existing document, pass either `merge=True` (merge all fields from the dict passed) or `merge=[list-of-fields]` (merge only the specified fields).

**Comment by adelespinasse** [comment]
The documentation is very confusing. If it's not possible to pass the option to `DocumentReference.update`, the documentation should say so. (It's also hard to find how to create the option argument; the documentation says it's a `WriteOption` but doesn't link to anything about that type.)

I wanted to use `update` with `write_option(exists=False)` so that I could use the path notation for merging, which doesn't seem to work with `.set(..., merge=True)`. So now, since I don't know whether the document will exist or not, I think I have to use a transaction. But it took some experimentation to figure that out. It would have been nice if the documentation just said so.

**Comment by DexterWSmith** [comment]
> The documentation is very confusing. If it's not possible to pass the option to `DocumentReference.update`, the documentation should say so. (It's also hard to find how to create the option argument; the documentation says it's a `WriteOption` but doesn't link to anything about that type.)
> 
> I wanted to use `update` with `write_option(exists=False)` so that I could use the path notation for merging, which doesn't seem to work with `.set(..., merge=True)`. So now, since I don't know whether the document will exist or not, I think I have to use a transaction. But it took some experimentation to figure that out. It would have been nice if the documentation just said so.

Facing the same issue as you are. Did you find out how to solve it without having to perform two operations?

**Comment by adelespinasse** [comment]
> Facing the same issue as you are. Did you find out how to solve it without having to perform two operations?

I don't remember, sorry. It might be helpful to search through the code, rather than trying to rely on the documentation. There's something for creating a WriteOption [here](https://github.com/googleapis/python-firestore/blob/801f8275899ea53c34f725f8a7629699f8b8ecbb/google/cloud/firestore_v1/base_client.py#L304) but I don't know if it works.
