### ISSUE TITLE
Spanner: Snapshot.execute_sql is missing from API docs

### ISSUE THREAD

**Issue by hegemonic** [googleapis/google-cloud-python#7607]
[`Snapshot.execute_sql`](https://github.com/googleapis/google-cloud-python/blob/5756bf3b8f6cc935849f928383959386def17dd3/spanner/google/cloud/spanner_v1/snapshot.py#L154) is missing from the [API docs for `Snapshot`](https://googleapis.github.io/google-cloud-python/latest/spanner/snapshot-api.html).

The public docs [tell developers to use this method](https://cloud.google.com/spanner/docs/getting-started/python/#using_the_client_library_for), so I suspect it should be in the API docs.

**Comment by tseaver** [comment]
Thanks for the report!  The reason that method (and others) doesn't appear is that it is defined on a base class, `_SnapshotBase`, which itself is private.  The fix is to change the Sphinx directive from `:show-inheritance:` to `:inherited-members:` in `docs/snapshot-api.rst` (and in `docs/transaction-api.rst` as well).

**Comment by hegemonic** [comment]
Thanks for fixing this issue so quickly!
