### ISSUE TITLE
Storage: retry operation

### ISSUE THREAD

**Issue by xmedeko** [googleapis/google-cloud-python#7907]
From my experience with other libs, storage operations rarely return HTTP 429 or 5xx retryable errors, e.g. see #3072 or [SO question](https://stackoverflow.com/questions/52304636)

 `api_core` has the `Retry` object, but I cannot find if it's used by the `storage.Client` or not? Should the top level functions have `retry` parameter? Furthemore, Google doc recommends to use (unmaintained!) [retrying lib](https://github.com/rholder/retrying), see https://cloud.google.com/storage/docs/exponential-backoff

It is connected with old storage client design #7762 ?

**Comment by tswast** [comment]
I think this can be a separate feature request from the client redesign. I agree that the client methods need `retry` arguments. This would align the storage client with our other clients.

**Comment by xmedeko** [comment]
Note, even `client.get_bucket('bucket-id')` has just returned 503 on the production. So, even this function should be retryable.

**Comment by crwilcox** [comment]
This is best done by starting from a design and then implementing.

**Comment by tvalentyn** [comment]
+1, we should strengthen storage client to retry on retriable errors with a back-off, here is an example where `get_bucket()` call fails with exception upon receiving HTTP 500:
```
...
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/storage/client.py", line 301, in get_bucket
    bucket.reload(client=self)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/storage/_helpers.py", line 130, in reload
    _target_object=self,
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 393, in api_request
    raise exceptions.from_http_response(response)
InternalServerError: 500 GET https://www.googleapis.com/storage/v1/b/msa-internal?projection=noAcl: Backend Error [while running 'Score Data']
```
It would be a much nicer user experience if the client itself attempted a retry, instead of making it a responsibility of the caller. To work around current behavior, callers may implement indiscriminate retries without a backoff, increasing the load on a system that may already experience a degraded performance.

**Comment by tseaver** [comment]
Tracked in #9298.
