### ISSUE TITLE
BigQuery: Decrease peak memory usage of `to_dataframe`

### ISSUE THREAD

**Issue by tswast** [googleapis/google-cloud-python#8107]
From: https://github.com/pydata/pandas-gbq/issues/275#issuecomment-494724625

__via `read_gbq(use_bqstorage_api=False)`__
![mem_test_baseball games_post_wide](https://user-images.githubusercontent.com/4090894/58162833-2e3fbd80-7c83-11e9-9d1b-c7b4ad593152.png)

__via `read_gbq(use_bqstorage_api=True)`__
![mem_test_gbq_storage_api](https://user-images.githubusercontent.com/4090894/58163635-9cd14b00-7c84-11e9-89c2-9c2d6135c536.png)

__via `fastavro`__
![mem_test_baseball games_post_wide avro](https://user-images.githubusercontent.com/4090894/58162859-3d267000-7c83-11e9-99e8-fe8291296b73.png)

__via `pd.read_csv(compression='gzip')`__
![mem_use_gzip](https://user-images.githubusercontent.com/4090894/58162900-50394000-7c83-11e9-9a6e-6b1356e764b3.png)

__via `pd.read_parquet(), using the gzip-imported dataframe -> exported as parquet as sourcefile__
![mem_test_parquet](https://user-images.githubusercontent.com/4090894/58162952-69da8780-7c83-11e9-929b-6b52bff9f558.png)

I suspect that if we `del` pages as we finish converting them to dataframe in the `to_dataframe` loop, we can decrease peak memory usage / overshoot by quite a lot.

**Comment by tswast** [comment]
Now that we're using pyarrow with the BQ Storage API, I suspect that memory usage has decreased by quite a bit.

It's worth re-running these tests to see if we can close this issue out.

**Comment by plamut** [comment]
I profiled the code again on the baseball public data using different BQ client versions and it appears that memory usage when calling `to_dataframe()` _without_ the BQ storage client has indeed decreased.

### Versions used
```
Python: 3.7.0+
pyarrow: 0.15.1
google-cloud-bigquery-storage: 0.7.0
```

### Test script
```py
from google.cloud import bigquery


@profile
def run_mem_test():
    client = bigquery.Client()

    table_path = "bigquery-public-data.baseball.games_post_wide"
    query_string = f"SELECT * from `{table_path}` LIMIT 4000"

    # Use the BigQuery Storage API to speed-up downloads of large tables.
    df = client.query(query_string).to_dataframe(create_bqstorage_client=False)  # or True

    print(df.info())
    print(f"Dataframe memory usage {table_path}: {df.memory_usage().sum()}")


if __name__ == "__main__":
    run_mem_test()
```

### Testing procedure
Install the tools:
```
$ pip install -U memory_profiler
$ pip install -U matplotlib
```
Run the profiler and visualize the results:
```
$ mprof run reproduce/iss_8107/reproduce_8107.py
$ mprof plot
```

I compared the current BigQuery client version from `master` with version `1.12.1` (the latest released version at the time this issue was created).

### Results

#### Option `create_bqstorage_client=False`:

_BigQuery client 1.21.1_
![to_dataframe_storage_api_False_BQ_1 12 1](https://user-images.githubusercontent.com/1235663/72729347-e1e8ac80-3b86-11ea-8cc4-0e6d933ed418.png)

_BigQuery client master_
![to_dataframe_storage_api_False_master](https://user-images.githubusercontent.com/1235663/72729349-e2814300-3b86-11ea-9fce-0b8992a8f7bc.png)

#### Option `create_bqstorage_client=True`:

_BigQuery client 1.21.1_
![to_dataframe_storage_api_True_BQ_1 12 1](https://user-images.githubusercontent.com/1235663/72729351-e2814300-3b86-11ea-9b5f-9e93db4540ee.png)

_BigQuery client master_
![to_dataframe_storage_api_True_master](https://user-images.githubusercontent.com/1235663/72729352-e2814300-3b86-11ea-9084-2e64de289562.png)


### Summary
There doesn't seem to be much difference when **not** using the bqstorage client, although the peak memory usage has decreased a bit.

On the other hand, memory savings are huge when bqstorage client is used. The latter used less than half as much memory on the test data.

**Comment by plamut** [comment]
@tswast I suppose the memory consumption improvement is large enough to close this issue?

**Comment by tswast** [comment]
> @tswast I suppose the memory consumption improvement is large enough to close this issue?

👍 

Let's close now that https://github.com/googleapis/google-cloud-python/issues/10185 is open, which will remove code paths where we have less control over memory usage.
