### ISSUE TITLE
BigQuery: Setting Connection Pool Size

### ISSUE THREAD

**Issue by dillonjohnson** [googleapis/google-cloud-python#8449]
We are trying to figure out how to up the possible connection pool size for the BigQuery Client. I'm not sure if this is a bug, but doing the below for https and http had no effect.

Thanks in advance!

BigQuery 
Running on a Docker Python:3.6-slim image
Version: google-cloud-bigquery==1.12.1

#### Steps to Reproduce

1. Open a Client Connection

2. Start multiple load jobs in parallel threads

3. Check output.

#### Code example

```python
    bq = bigquery.Client(project=project)

    bq._http.adapters['https://']._pool_connections = 100

    load_job = bq.load_table_from_uri(
        source_uris=f'gs://{bucket.name}/dart/{extraction_name}/data/{seg_id}_*',
        destination=bigquery.TableReference.from_string(f'{project}.{dataset_id}.{table_id}'),
        job_config=job_config)
```

#### Stack Trace
```
{{connectionpool.py:275}} WARNING - Connection pool is full, discarding connection: www.googleapis.com
```

**Comment by tseaver** [comment]
The [`requests.adapters.HTTPAdapter` class](https://2.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter) takes three pool-related parameters:

- `pool_connections`:  number of `urllib3` connection pools
- `pool_maxsize`: maximum number of connections in a given pool
- `pool_block`: whether to block when requesting another connection after reaching `pool_maxsize`.

In your case, the warning is occurring because you have the default `pool_maxsize` (10), `pool_block` is False (the default), and so the extra connections are being discarded, rather than returned to the pool.  You need to configure `pool_maxsize`, rather than (or in addition to) `pool_connections`.

**Comment by dillonjohnson** [comment]
Okay. Thanks.

Now I understand the difference, however I've tried all of these with no change in behavior.

```python
bq._http.adapters['https://']._pool_connections = 200
bq._http.adapters['https://']._pool_maxsize = 200
bq._http.adapters['http://']._pool_maxsize = 200
bq._http.adapters['http://']._pool_connections = 200
bq._http_internal.adapters['https://']._pool_maxsize=100
bq._http_internal.adapters['https://']._pool_connections = 100
bq._http_internal.adapters['http://']._pool_maxsize = 100
bq._http_internal.adapters['http://']._pool_connections = 100
```

For example if I use 16 threads, I encounter the same warnings. Is there a different syntax I should be using here other than directly modifying these?

**Comment by InbarRose** [comment]
I would also like to know if there is a more convenient/canonical way to adjust these parameters

**Comment by toships** [comment]
The http connection pool is the right solution but couldnt get that working and it seems experimental from the [docs](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html?highlight=_http). 

I am using this work around - it spaws threads and each thread has a new bq object. You would have to consider limiting the threads to what your underlying hardware etc can support but this can do more than 10 queries which is the number limited by the default connection pool manager. 

Thought I will share, maybe this helps you. 

`import threading 

#### Creating multiple query strings and storing it in a list 
temp_json = request_json.copy()
del_query_strs = []

delete_query_str = '''
DELETE FROM `{project_name}.{dataset_name}.{table_name}`
WHERE timestamp = "{date}"
'''
for t in tables_to_create:
    temp_json['table_name'] = t 
    query_str = delete_query_str.format_map(temp_json)
    del_query_strs.append(query_str)

#### Setting up threading (value here can specify the max threads) 
pool_sema = threading.BoundedSemaphore(value=30) 
jobs_done = dict()

def make_bq_call(query_str, pool_sema):
    global jobs_done
    logging.debug(f'Enter: {query_str}' )
    with pool_sema:
        bqclient = bigquery.Client()  # this creates new instance hence has a pool of 10 
        job = bqclient.query(
            query_str
        )
        job.result()
        jobs_done[job.job_id] = True
        logger.debug(f'Done: {job.job_id} - total: {sum(jobs_done.values())} of {len(jobs_done)} finished' )
        
# starting all the threads - note the pool_sema will make sure there are only 30 threads active any time in this case 
for query_str in del_query_strs:
    t = threading.Thread(
        target=make_bq_call,
        args=(query_str, pool_sema),
    )
    t.start()
        
#### waiting for all the threads to be done before moving forward 
while sum(jobs_done.values()) < len(del_query_strs) :
    logging.info(
        f"Waiting for Jobs to finish - Delete - {sum(jobs_done.values())} of {len(del_query_strs)} finished"
    )
    sleep(1)
logging.info(f"Done Delete - {sum(jobs_done.values())} of {len(jobs_done)} finished")`

**Comment by smills17** [comment]
confirming this bug is still present.

it appears that these values are not changeable after initialization.

I'm trying to hack my own _http object in there during init by doing something like:

`from requests.adapters import HTTPAdapter
from google.cloud.bigquery import Client

client = Client(
project_id,
_http=HTTPAdapter(
pool_connections=100,
pool_maxsize=100,
max_retries=10,
pool_block=False)
)
`
It lets me initialize the client like this, but as soon as I try to use it:

`AttributeError: 'HTTPAdapter' object has no attribute 'request'`

**Comment by tseaver** [comment]
Current development on the Python `google-cloud-bigquery` client library has moved to the https://github.com/googleapis/python-bigquery/ repository.  Please follow up there.
