### ISSUE TITLE
Firestore: Generate Admin V1 Client.

### ISSUE THREAD

**Issue by BenWhitehead** [googleapis/google-cloud-python#8664]
Adding the Firestore Admin API Client will allow programmatic management of indexes, and export/import operations.

* Artman config: [artman_firestore_v1.yaml](https://github.com/googleapis/googleapis/blob/master/google/firestore/admin/artman_firestore_v1.yaml)

Feel free to ping me if any updates are needed for the artman file.

b/129353554

**Comment by tseaver** [comment]
Supersedes #6334.

**Comment by tseaver** [comment]
@BenWhitehead One question:  is there any requirement to tweak the admin client surface, or is this a pure autogen client?

**Comment by tseaver** [comment]
@BenWhitehead I do need a change in `googleapis`:  please see https://github.com/googleapis/googleapis/pull/566.

Rationale: the gapic-genrator is dumping the protoc-generated Python files in `~/.cache/synthtool/googleapis/artman-genfiles/python/firestore-admin-v1/google/cloud/firestore_v1`, rather than the expected `.cache/synthtool/googleapis/artman-genfiles/python/firestore-admin-v1/google/cloud/firestore_admin_v1/`, where it copies the actual .proto files.

For comparison, see: https://github.com/googleapis/googleapis/blob/47bd0c2ba33c28dd624a65dad382e02bb61d1618/google/bigtable/admin/v2/bigtableadmin_gapic.yaml#L10
