### ISSUE TITLE
BigQuery DataTransfer: Config doesn't support notifications.

### ISSUE THREAD

**Issue by sheldongill** [googleapis/google-cloud-python#8811]
When creating a transfer through the UI, it's possible to set a pubsub topic to receive notifications and also e-mail.

Listing those doesn't return any corresponding fields.

#### Environment details

1.  Using create_transfer_config() list_transfer_configs() and refering to API documentation: https://cloud.google.com/bigquery/docs/reference/datatransfer/rest/v1/projects.locations.transferConfigs#TransferConfig
2. MacOS 10.14.5 and Ubuntu 18.04
3. Python 3.7.4
4. google-cloud-bigquery-datatransfer==0.4.0

#### Steps to reproduce

Create a transfer service through the UI specifying a Notification Pub/Sub topic and email notifications.

Call list_transfer_configs() to get the list and look at the returned objects.
There's nothing about the notifications even though they're listed under "Transfer config details"
The API reports:
Available Fields(except extensions): ['name', 'destinationDatasetId', 'displayName', 'dataSourceId', 'params', 'schedule', 'scheduleOptions', 'dataRefreshWindowDays', 'disabled', 'updateTime', 'nextRunTime', 'state', 'userId', 'datasetRegion']

**Comment by sheldongill** [comment]
This means we can't programmatically create transfers with notifications enabled :(

**Comment by tseaver** [comment]
@sheldongill The API docs you linked are for the REST endpoint, while the `google-cloud-bigquery-datatransfer` library uses the [gRPC endpoint](https://cloud.google.com/bigquery/docs/reference/datatransfer/rpc/google.cloud.bigquery.datatransfer.v1#google.cloud.bigquery.datatransfer.v1.TransferConfig).

Neither of them, however, surface an attribute for a pubsub topic to be notified.  Without that support, we can't do anything here in the client library.

The [docs for transfer notifications](https://cloud.google.com/bigquery/docs/transfer-run-notifications) do state that the feature has `alpha` support:

>  This product or feature is in a pre-release state and might change or have limited support.

You could lobby to have the feature surfaced in the API using one of the [BigQuery support resources](https://cloud.google.com/bigquery/support).  Because the library is autogenerated, once the `.proto` files include the notification field(s), support for the feature will appear here.

**Comment by ccao93** [comment]
Hi @tseaver, I have created a feature request and was notified the API has been enabled last Friday. May I ask how long it would take for this feature to be added to this Python SDK? Thanks

**Comment by tseaver** [comment]
@ccao93 Current development of the Python `google-cloud-bigquery-datatransfer` library has move to the https://github.com/googleapis/python-bigquery-datatransfer/ repository Please follow up there.
