### ISSUE TITLE
KMS: Documentation link on `googleapis.dev`  is missing.

### ISSUE THREAD

**Issue by di** [googleapis/google-cloud-python#8993]
In #8705 the "Client Library Documentation" link in the `google-cloud-kms` README was changed from https://googleapis.github.io/google-cloud-python/latest/kms/index.html to https://googleapis.dev/python/kms/latest, but the latter does not exist.

Ref: https://issuetracker.google.com/issues/139095461

**Comment by tseaver** [comment]
The following are invalid "client library documentation" URLs linked into READMES:

- asset: https://googleapis.dev/python/asset/latest
- kms: https://googleapis.dev/python/kms/latest
- monitoring: https://google-cloud-python.readthedocs.io/en/latest/monitoring/
- scheduler: https://googleapis.dev/python/scheduler/latest
- tasks: https://googleapis.dev/python/tasks/latest
- trace: https://googleapis.dev/python/trace/latest

The one for `monitoring` hasn't been converted, now fixed in #8994.

@busunkim96 Can you help figure out why the others are broken?
