### ISSUE TITLE
Firestore: Invalid handling of timezones

### ISSUE THREAD

**Issue by tsteinruecken** [googleapis/google-cloud-python#9025]
I believe to have found a bug in the python firestore client library that causes datetime objects to be corrupted when first written to firestore.

In Python, dates returned from datetime.now() are in the local timezone (=wallclock time). However i suspect the firestore to expect dates stored as UTC. But the Client-Library does not seem to convert that local datetime to utc before writing it to the firestore.

As time of testing it was 12:53 (GMT+2) here in Germany (thats 10:53am UTC). That was the date i've written to firestore. The Read directly afterwards yields the same values, but timezone is set to UTC. If i read the same value in the firebase console it shows as 14:53 UTC+2. Accessing the value using go yields 12:53 UTC (same as Python, correct values, wrong timezone) while ruby yields 14:53 +0200. So the mismatch seems to happen during write from python.

Probably this bug surfaces only if you actually evaluate the timezone and run your code from a machine that is not set to UTC (luckily appengine is set to utc).

I believe this bug is in https://github.com/googleapis/google-cloud-python/blob/083ee9cca48663d5c2829c66f7d60c8be23be2b1/core/google/cloud/_helpers.py#L215, calendar.timegm seems to yield local timestamps while time.mktime correctly transforms it to UTC Epoc.

#### Environment details

Tested on Python 3.6.8 (default, Mar 21 2019, 10:08:12) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)] on linux
Firestore Version (firestore.__version__): 1.4.0

#### Steps to reproduce

  1. Run testcode below or run the example at https://github.com/GoogleCloudPlatform/python-docs-samples/blob/f615b6ad0391c1307de403adf53b2ac93c1e66a5/firestore/cloud-client/snippets.py#L90 on any machine not set to UTC
  2. Verify the Date in Firebase console

#### Code example

```python
from google.cloud import firestore
import datetime

now = datetime.datetime.now()
print("Firestore Version is: %s" % firestore.__version__)
print("Current time written to firestore: %s" % now.isoformat())

db = firestore.Client()
doc_ref = db.collection("testdoc").document(u'testdoc')
doc_ref.set({
    u'testdate': now,
})

testdoc_ref = db.collection(u'testdoc')
docs = testdoc_ref.stream()

for doc in docs:
    print(u'{} => {}'.format(doc.id, doc.to_dict()))

```

**Comment by tseaver** [comment]
In your example, the time you construct using `datetime.datetime.now()` is indeed in the local time for the machine, but it does *not* include any timezone:  it is what the [Python docs](https://docs.python.org/2/library/datetime.html) call a "naive" datetime object.

Firestore documents require timestamp fields to be passed as seconds since the UTC epoch, which means we *must* convert any datetime value to UTC.  For "naive" datetimes, we therefore assume that the value is in UTC already.  To make your example work, either:

- Explicitly assign a timezone, e.g.: `now = datetime.datetime.now(tz=your_tzinfo)`
- Construct the naive time in UTC, e.g.: `now = datetime.datetime.utcnow()`
