### ISSUE TITLE
BigQuery Data Transfer: Can't use "create_transfer_config" on cloud functions

### ISSUE THREAD

**Issue by eknis** [googleapis/google-cloud-python#9359]
Hello,
I use your google.cloud.bigquery_datatransfer_v1 library on cloud functions.
While using `create_transfer_config` method I had a trouble with the permission.

# The example code
```
# requirements.txt
google-cloud-bigquery-datatransfer
```
```
from google.cloud import bigquery_datatransfer_v1
client = bigquery_datatransfer_v1.DataTransferServiceClient()

parent = client.location_path({PROJECT}, {LOCATION})

params = {
    {PARAMS}
}
    
struct_params = Struct()
struct_params.update(params)

transfer_config = {
    "display_name": "YourScheduledQueryName",
    "data_source_id": "google_cloud_storage",
    "destination_dataset_id": "test",
    "schedule": "every day 01:00",
    "params": struct_params
}

client.create_transfer_config(parent, transfer_config)
```

# output
```
Error: function crashed. Details:
400 P4 service account needs iam.serviceAccounts.getAccessToken permission. Running the following command may resolve this error: gcloud projects  add-iam-policy-binding <PROJECT_ID> --member='serviceAccount:service-<PROJECT_NUMBER>@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com' --role='roles/iam.serviceAccountShortTermTokenMinter'
```

I tried `add-iam-policy-binding`, however it still output same.

# Expected output
success for creating, or show exact problem.

**Comment by tswast** [comment]
@eknis Thanks for your patience. The permissions for using BQ-DTS with service account permissions are tricky to get right. It's currently considered a Beta feature to use BQ-DTS with service accounts in this way.

The following need to be true:

* Your service account needs *owner* permissions on the target dataset. This is because it needs to be able to grant write permissions to an internal BQ-DTS service account.
* A service account `service-PROJECT_NUMBER@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com` needs permissions to create access tokens on behalf of your service account.

To grant token create permissions (replace `${PROJECT_ID}` and `${PROJECT_NUMBER}` with values matching your GCP project):

```
gcloud projects add-iam-policy-binding "${PROJECT_ID}" \
    --member='serviceAccount:service-'"${PROJECT_NUMBER}"'@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com' \
    --role='roles/iam.serviceAccountShortTermTokenMinter'
```

**Comment by eknis** [comment]
@tswast 
Thank you for answering!

**Comment by NicolaSpreafico** [comment]
Hi, same problem here.

When you say

> Your service account needs owner permissions on the target dataset. This is because it needs to be able to grant write permissions to an internal BQ-DTS service account.

You mean _BigQuery Data Owner_ role or total _Project Owner_ ?

In my case I'm using a service-account created by a project different from the project where I'm trying to create the scheduled-query. This service-account is _BigQuery Admin_ on the destination project. Which service-account should I configure as _serviceAccountShortTermTokenMinter_ and in which project? The one that created the service-account or the one where I'm trying to create the scheduled query=
