### ISSUE TITLE
spanner: Session pool should hand out sessions in LIFO order

### ISSUE THREAD

**Issue by skuruppu** [googleapis/google-cloud-python#9392]
**Is your feature request related to a problem? Please describe.**
Currently sessions are handed out from the session pool in FIFO order. Least recently used sessions are unlikely to be in backend caches, and the transactions associated with them are likely to aborted due to idleness.

**Describe the solution you'd like**
The session pool should hand out sessions in LIFO order.

**Comment by tseaver** [comment]
For the `FixedSizePoot` and `BurstyPool` classes, this change is straightforward:  we just use `queue.LifoQueue` instead of `queue.Queue` for the sessions.

For the `PingingPool` and `TransacctionPingingPool` class, the issue isn't quite clear:  sessions are held in a priority queue based on when they need to be "pinged" (checked for existence at intervals).
